### ISSUE TITLE
Missing Loss_TVReg file

### ISSUE THREAD

**Issue by jessicaloohw** [abhi4ssj/ReLayNet#1]
Hi, I am trying to deploy `EnsembleTest` but it is unable to run due to the missing `Loss_TVReg` function which should be in the dagnn wrappers folder, I think. Thank you!

**Comment by abhi4ssj** [comment]
Hi,
I uploaded the Loss_TVReg wrapper. You can use it now.

Best
Abhijit

**Comment by jessicaloohw** [comment]
Thank you!
